from text_clusterer import get_clusters
# Load messages
messages = [
    "Hello, how are you today?",
    "What's the weather like where you are?",
    "Have you watched any good movies or TV shows lately?",
    "Do you have any plans for the weekend?",
    "What's your favorite type of cuisine?",
    "Do you prefer cats or dogs?",
    "Have you read any good books lately?",
    "What's your favorite hobby?",
    "What kind of music do you enjoy listening to?",
    "Have you ever traveled outside of your country?",
    "What's your favorite season?",
    "Do you have any pets?",
    "What's your favorite type of food?",
    "What's your favorite TV show?",
    "What's your favorite movie?",
    "Do you enjoy cooking?",
    "What's your favorite book?",
    "Do you like going to the beach?",
    "What's your favorite sport?",
    "Have you ever gone camping?",
    "What's your favorite type of dessert?",
    "Do you like to dance?",
    "What's your favorite type of exercise?",
    "Do you prefer the city or the countryside?",
    "What's your favorite color?",
    "Do you have any siblings?",
    "What's your favorite type of flower?",
    "Have you ever gone skiing or snowboarding?",
    "What's your favorite holiday?",
    "Do you like to travel?",
    "What's your favorite type of tree?",
    "Do you prefer coffee or tea?",
    "What's your favorite type of bread?",
    "Do you like to watch sports?",
    "What's your favorite animal?",
    "Do you enjoy going to museums?",
    "What's your favorite type of pizza?",
    "What's your favorite type of pasta?",
    "Do you like to hike?",
    "What's your favorite type of cheese?",
    "Have you ever gone on a cruise?",
    "What's your favorite type of cake?",
    "Do you enjoy gardening?",
    "What's your favorite type of wine?",
    "Do you like to shop?",
    "What's your favorite type of chocolate?",
    "What's your favorite type of tea?",
    "Do you like to swim?",
    "What's your favorite type of ice cream?",
    "Have you ever gone bungee jumping?",
    "What's your favorite type of fish?",
    "Do you like to go to the gym?",
    "What's your favorite type of vegetable?",
    "What's your favorite type of fruit?",
    "Do you like to go to the zoo?",
    "What's your favorite type of bird?",
    "Have you ever gone skydiving?",
    "What's your favorite type of nut?",
    "Do you like to go to the theater?",
    "What's your favorite type of beer?",
    "What's your favorite type of cocktail?",
    "Do you like to go to concerts?",
    "What's your favorite type of soda?",
    "What's your favorite type of juice?",
    "Do you like to go to amusement parks?",
    "What's your favorite type of sandwich?",
    "What's your favorite type of soup?",
    "Do you like to go to the opera?",
    "What's your favorite type of liquor?",
    "What's your favorite type of salad?",
    "Do you like to go to the ballet?",
    "What's your favorite type of meat?",
    "What's your favorite type of seafood?",
    "Do you like to go to the circus?",
    "What's your favorite type of coffee?",
    "What's your favorite type of tea?",
    "Do you like to go to the movies?",
    "Hello, how are you today?",
    "What's the weather like where you are?",
    "Have you watched any good movies or TV shows lately?",
    "Do you have any plans for the weekend?",
    "What's your favorite type of cuisine?",
    "Do you prefer cats or dogs?",
    "Have you read any good books lately?",
    "What's your favorite hobby?",
    "What kind of music do you enjoy listening to?",
    "Have you ever traveled outside of your country?",
    "What's your favorite season?",
    "Do you have any pets?",
    "What's your favorite type of food?",
    "What's your favorite TV show?",
    "What's your favorite movie?",
    "Do you enjoy cooking?",
    "What's your favorite book?",
    "Do you like going to the beach?",
    "What's your favorite sport?",
    "Have you ever gone camping?",
    "What's your favorite type of dessert?",
    "Do you like to dance?",
    "What's your favorite type of exercise?",
    "Do you prefer the city or the countryside?",
    "What's your favorite color?",
    "Do you have any siblings?",
    "What's your favorite type of flower?",
    "Have you ever gone skiing or snowboarding?",
    "What's your favorite holiday?",
    "Do you like to travel?",
    "What's your favorite type of tree?",
    "Do you prefer coffee or tea?",
    "What's your favorite type of bread?",
    "Do you like to watch sports?",
    "What's your favorite animal?",
    "Do you enjoy going to museums?",
    "What's your favorite type of pizza?",
    "What's your favorite type of pasta?",
    "Do you like to hike?",
    "What's your favorite type of cheese?",
    "Have you ever gone on a cruise?",
    "What's your favorite type of cake?",
    "Do you enjoy gardening?",
    "What's your favorite type of wine?",
    "Do you like to shop?",
    "What's your favorite type of chocolate?",
    "What's your favorite type of tea?",
    "Do you like to swim?",
    "What's your favorite type of ice cream?",
    "Have you ever gone bungee jumping?",
    "What's your favorite type of fish?",
    "Do you like to go to the gym?",
    "What's your favorite type of vegetable?",
    "What's your favorite type of fruit?",
    "Do you like to go to the zoo?",
    "What's your favorite type of bird?",
    "Have you ever gone skydiving?",
    "What's your favorite type of nut?",
    "Do you like to go to the theater?",
    "What's your favorite type of beer?",
    "What's your favorite type of cocktail?",
    "Do you like to go to concerts?",
    "What's your favorite type of soda?",
    "What's your favorite type of juice?",
    "Do you like to go to amusement parks?",
    "What's your favorite type of sandwich?",
    "What's your favorite type of soup?",
    "Do you like to go to the opera?",
    "What's your favorite type of liquor?",
    "What's your favorite type of salad?",
    "Do you like to go to the ballet?",
    "What's your favorite type of meat?",
    "What's your favorite type of seafood?",
    "Do you like to go to the circus?",
    "What's your favorite type of coffee?",
    "What's your favorite type of tea?",
    "Do you like to go to the movies?",
    "Hello, how are you today?",
    "What's the weather like where you are?",
    "Have you watched any good movies or TV shows lately?",
    "Do you have any plans for the weekend?",
    "What's your favorite type of cuisine?",
    "Do you prefer cats or dogs?",
    "Have you read any good books lately?",
    "What's your favorite hobby?",
    "What kind of music do you enjoy listening to?",
    "Have you ever traveled outside of your country?",
    "What's your favorite season?",
    "Do you have any pets?",
    "What's your favorite type of food?",
    "What's your favorite TV show?",
    "What's your favorite movie?",
    "Do you enjoy cooking?",
    "What's your favorite book?",
    "Do you like going to the beach?",
    "What's your favorite sport?",
    "Have you ever gone camping?",
    "What's your favorite type of dessert?",
    "Do you like to dance?",
    "What's your favorite type of exercise?",
    "Do you prefer the city or the countryside?",
    "What's your favorite color?",
    "Do you have any siblings?",
    "What's your favorite type of flower?",
    "Have you ever gone skiing or snowboarding?",
    "What's your favorite holiday?",
    "Do you like to travel?",
    "What's your favorite type of tree?",
    "Do you prefer coffee or tea?",
    "What's your favorite type of bread?",
    "Do you like to watch sports?",
    "What's your favorite animal?",
    "Do you enjoy going to museums?",
    "What's your favorite type of pizza?",
    "What's your favorite type of pasta?",
    "Do you like to hike?",
    "What's your favorite type of cheese?",
    "Have you ever gone on a cruise?",
    "What's your favorite type of cake?",
    "Do you enjoy gardening?",
    "What's your favorite type of wine?",
    "Do you like to shop?",
    "What's your favorite type of chocolate?",
    "What's your favorite type of tea?",
    "Do you like to swim?",
    "What's your favorite type of ice cream?",
    "Have you ever gone bungee jumping?",
    "What's your favorite type of fish?",
    "Do you like to go to the gym?",
    "What's your favorite type of vegetable?",
    "What's your favorite type of fruit?",
    "Do you like to go to the zoo?",
    "What's your favorite type of bird?",
    "Have you ever gone skydiving?",
    "What's your favorite type of nut?",
    "Do you like to go to the theater?",
    "What's your favorite type of beer?",
    "What's your favorite type of cocktail?",
    "Do you like to go to concerts?",
    "What's your favorite type of soda?",
    "What's your favorite type of juice?",
    "Do you like to go to amusement parks?",
    "What's your favorite type of sandwich?",
    "What's your favorite type of soup?",
    "Do you like to go to the opera?",
    "What's your favorite type of liquor?",
    "What's your favorite type of salad?",
    "Do you like to go to the ballet?",
    "What's your favorite type of meat?",
    "What's your favorite type of seafood?",
    "Do you like to go to the circus?",
    "What's your favorite type of coffee?",
    "What's your favorite type of tea?",
    "Do you like to go to the movies?",
    "Hello, how are you today?",
    "What's the weather like where you are?",
    "Have you watched any good movies or TV shows lately?",
    "Do you have any plans for the weekend?",
    "What's your favorite type of cuisine?",
    "Do you prefer cats or dogs?",
    "Have you read any good books lately?",
    "What's your favorite hobby?",
    "What kind of music do you enjoy listening to?",
    "Have you ever traveled outside of your country?",
    "What's your favorite season?",
    "Do you have any pets?",
    "What's your favorite type of food?",
    "What's your favorite TV show?",
    "What's your favorite movie?",
    "Do you enjoy cooking?",
    "What's your favorite book?",
    "Do you like going to the beach?",
    "What's your favorite sport?",
    "Have you ever gone camping?",
    "What's your favorite type of dessert?",
    "Do you like to dance?",
    "What's your favorite type of exercise?",
    "Do you prefer the city or the countryside?",
    "What's your favorite color?",
    "Do you have any siblings?",
    "What's your favorite type of flower?",
    "Have you ever gone skiing or snowboarding?",
    "What's your favorite holiday?",
    "Do you like to travel?",
    "What's your favorite type of tree?",
    "Do you prefer coffee or tea?",
    "What's your favorite type of bread?",
    "Do you like to watch sports?",
    "What's your favorite animal?",
    "Do you enjoy going to museums?",
    "What's your favorite type of pizza?",
    "What's your favorite type of pasta?",
    "Do you like to hike?",
    "What's your favorite type of cheese?",
    "Have you ever gone on a cruise?",
    "What's your favorite type of cake?",
    "Do you enjoy gardening?",
    "What's your favorite type of wine?",
    "Do you like to shop?",
    "What's your favorite type of chocolate?",
    "What's your favorite type of tea?",
    "Do you like to swim?",
    "What's your favorite type of ice cream?",
    "Have you ever gone bungee jumping?",
    "What's your favorite type of fish?",
    "Do you like to go to the gym?",
    "What's your favorite type of vegetable?",
    "What's your favorite type of fruit?",
    "Do you like to go to the zoo?",
    "What's your favorite type of bird?",
    "Have you ever gone skydiving?",
    "What's your favorite type of nut?",
    "Do you like to go to the theater?",
    "What's your favorite type of beer?",
    "What's your favorite type of cocktail?",
    "Do you like to go to concerts?",
    "What's your favorite type of soda?",
    "What's your favorite type of juice?",
    "Do you like to go to amusement parks?",
    "What's your favorite type of sandwich?",
    "What's your favorite type of soup?",
    "Do you like to go to the opera?",
    "What's your favorite type of liquor?",
    "What's your favorite type of salad?",
    "Do you like to go to the ballet?",
    "What's your favorite type of meat?",
    "What's your favorite type of seafood?",
    "Do you like to go to the circus?",
    "What's your favorite type of coffee?",
    "What's your favorite type of tea?",
    "Do you like to go to the movies?",
]

num_clusters, cluster_messages = get_clusters(messages, 308)

for i in range(num_clusters):
    print("Cluster", i, "messages:")
    for message in cluster_messages[i]:
        print("-", message)
